// Maps spoken/typed variations to the Exact Key in your JSON file
export const BOOK_ALIASES = {
  // Old Testament
  "genesis": "Genesis", "gen": "Genesis", "ge": "Genesis",
  "exodus": "Exodus", "ex": "Exodus",
  "leviticus": "Leviticus", "lev": "Leviticus",
  "numbers": "Numbers", "num": "Numbers",
  "deuteronomy": "Deuteronomy", "deut": "Deuteronomy", "dt": "Deuteronomy",
  "joshua": "Joshua", "josh": "Joshua",
  "judges": "Judges", "judg": "Judges",
  "ruth": "Ruth", "root": "Ruth", "roots": "Ruth",
  "1 samuel": "1 Samuel", "first samuel": "1 Samuel", "1st samuel": "1 Samuel", "1 sa": "1 Samuel", "1 sam": "1 Samuel",
  "2 samuel": "2 Samuel", "second samuel": "2 Samuel", "2nd samuel": "2 Samuel", "2 sa": "2 Samuel", "2 sam": "2 Samuel",
  "1 kings": "1 Kings", "first kings": "1 Kings", "1st kings": "1 Kings", "1 ki": "1 Kings",
  "2 kings": "2 Kings", "second kings": "2 Kings", "2nd kings": "2 Kings", "2 ki": "2 Kings",
  "1 chronicles": "1 Chronicles", "first chronicles": "1 Chronicles", "1st chronicles": "1 Chronicles", "1 chron": "1 Chronicles",
  "2 chronicles": "2 Chronicles", "second chronicles": "2 Chronicles", "2nd chronicles": "2 Chronicles", "2 chron": "2 Chronicles",
  "ezra": "Ezra",
  "nehemiah": "Nehemiah", "neh": "Nehemiah",
  "esther": "Esther", "esta": "Esther", "ester": "Esther", "est": "Esther",
  "job": "Job",

  // FIX: Psalms variations
  "psalms": "Psalms", "psalm": "Psalms", "ps": "Psalms", "sam": "Psalms", "some": "Psalms", "sum": "Psalms", "songs": "Psalms", "sound": "Psalms",

  "proverbs": "Proverbs", "prov": "Proverbs", "pr": "Proverbs",
  "ecclesiastes": "Ecclesiastes", "eccl": "Ecclesiastes",

  // FIX: Song of Solomon variations
  "song of solomon": "Song of Solomon", "songs of solomon": "Song of Solomon", "song of songs": "Song of Solomon", "canticles": "Song of Solomon", "sos": "Song of Solomon", "sons of solomon": "Song of Solomon", "son of solomon": "Song of Solomon",

  "isaiah": "Isaiah", "isa": "Isaiah",
  "jeremiah": "Jeremiah", "jer": "Jeremiah",
  "lamentations": "Lamentations", "lam": "Lamentations",
  "ezekiel": "Ezekiel", "ezek": "Ezekiel",
  "daniel": "Daniel", "dan": "Daniel",
  "hosea": "Hosea", "hos": "Hosea", "osia": "Hosea", "ozia": "Hosea", "jose": "Hosea",
  "joel": "Joel", "jewel": "Joel", "joe": "Joel",
  "amos": "Amos", "am": "Amos",
  "obadiah": "Obadiah", "obad": "Obadiah", "obadaya": "Obadiah", "openaya": "Obadiah", "over there": "Obadiah",
  "jonah": "Jonah", "jnh": "Jonah",
  "micah": "Micah", "mic": "Micah", "mica": "Micah", "mike": "Micah",
  "nahum": "Nahum", "nah": "Nahum", "nahin": "Nahum", "now home": "Nahum", "no home": "Nahum",
  "habakkuk": "Habakkuk", "hab": "Habakkuk", "haba cook": "Habakkuk", "habacook": "Habakkuk", "habakuk": "Habakkuk",
  "zephaniah": "Zephaniah", "zeph": "Zephaniah", "zephania": "Zephaniah",
  "haggai": "Haggai", "hag": "Haggai", "hagai": "Haggai", "guy": "Haggai",
  "zechariah": "Zechariah", "zech": "Zechariah",
  "malachi": "Malachi", "mal": "Malachi",

  // New Testament
  "matthew": "Matthew", "matt": "Matthew", "mt": "Matthew", "math": "Matthew",
  "mark": "Mark", "mk": "Mark",
  "luke": "Luke", "lk": "Luke",
  "john": "John", "jn": "John",
  "acts": "Acts", "act": "Acts", "acts of the apostles": "Acts", "acts of the posters": "Acts",
  "romans": "Romans", "rom": "Romans", "roman": "Romans",
  "1 corinthians": "1 Corinthians", "first corinthians": "1 Corinthians", "1st corinthians": "1 Corinthians", "1 cor": "1 Corinthians",
  "2 corinthians": "2 Corinthians", "second corinthians": "2 Corinthians", "2nd corinthians": "2 Corinthians", "2 cor": "2 Corinthians",
  "galatians": "Galatians", "gal": "Galatians",
  "ephesians": "Ephesians", "eph": "Ephesians",
  "philippians": "Philippians", "phil": "Philippians",
  "colossians": "Colossians", "col": "Colossians",
  "1 thessalonians": "1 Thessalonians", "first thessalonians": "1 Thessalonians", "1st thessalonians": "1 Thessalonians", "1 thess": "1 Thessalonians",
  "2 thessalonians": "2 Thessalonians", "second thessalonians": "2 Thessalonians", "2nd thessalonians": "2 Thessalonians", "2 thess": "2 Thessalonians",
  "1 timothy": "1 Timothy", "first timothy": "1 Timothy", "1st timothy": "1 Timothy", "1 tim": "1 Timothy",
  "2 timothy": "2 Timothy", "second timothy": "2 Timothy", "2nd timothy": "2 Timothy", "2 tim": "2 Timothy",
  "titus": "Titus", "tit": "Titus",
  "philemon": "Philemon", "phlm": "Philemon",
  "hebrews": "Hebrews", "heb": "Hebrews",
  "james": "James", "jas": "James",
  "1 peter": "1 Peter", "first peter": "1 Peter", "1st peter": "1 Peter", "1 pet": "1 Peter",
  "2 peter": "2 Peter", "second peter": "2 Peter", "2nd peter": "2 Peter", "2 pet": "2 Peter",
  "1 john": "1 John", "first john": "1 John", "1st john": "1 John", "1 jn": "1 John",
  "2 john": "2 John", "second john": "2 John", "2nd john": "2 John", "2 jn": "2 John",
  "3 john": "3 John", "third john": "3 John", "3rd john": "3 John", "3 jn": "3 John",
  "jude": "Jude", "judy": "Jude",
  "revelation": "Revelation", "revelations": "Revelation", "rev": "Revelation"
};